### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by adamnewtonwright** [boohann/Laser-Rate-Equations-Python#1]
Line 74 has a small typo. The "L" in "Laser_rates" should be a lower case. It should be switched from this:

`r = ode(Laser_rates).set_integrator('dopri5', nsteps = 1e4)`

to

`r = ode(laser_rates).set_integrator('dopri5', nsteps = 1e4)`

**Comment by boohann** [comment]
I missed that error, thank you!

Niall
